### ISSUE TITLE
Luna 64K problem with the texture and mesh (KSRSS)

### ISSUE THREAD

**Issue by BlackDinosShadows** [ballisticfox/Luna64k#1]
When i'm in the tracking station the moon appears totally black , and when I'm landed on it more I dezoom more the moon disappears and when I'm at max dezoom it return with black texture , is my parameters not good or it's an other thing ?
Thank you in advance.

**Comment by BlackDinosShadows** [comment]
here's the problems
![screenshot2](https://github.com/ballisticfox/KSP-64k/assets/122492579/100dfe83-b297-48b6-bb7d-74f74fef7129)
and

https://github.com/ballisticfox/KSP-64k/assets/122492579/25da5d51-f113-48b8-8f79-5075af9f134a

**Comment by ballisticfox** [comment]
Are you using the custom Kopernicus fork?

**Comment by BlackDinosShadows** [comment]
Yes your kopernicus 1F

**Comment by ballisticfox** [comment]
Can you send your KSP.log?

Do you happen to be playing on macOS?

**Comment by BlackDinosShadows** [comment]
[KSP.log](https://github.com/ballisticfox/KSP-64k/files/12395295/KSP.log)
No, This log is with RSS, I tested it and it have the same problem.
I'm playing on windows.

**Comment by rp1-lox** [comment]
This also occurs for me using the 2F version.

**Comment by dandoesgithub** [comment]
happens to me using the 3F version

**Comment by BlackDinosShadows** [comment]
Okay with the 3f i discovered that the black texture came from me cause i installed kopernicus on ckan and after i put the fork one without deleting the old one but when i installed it deleting the old one and replace it with the fork , now the texture is here (so this is solved) but I always have the fade problem ,I will try to modify the fade in the config and come if it work

**Comment by BlackDinosShadows** [comment]
It worked this previous mistake is solved and now the moons appear without doing this thing just by modifying the distances of fade in and out,so now my problem is solved thank you Ballisticfox
